apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: keycloak-backend-config
  namespace: essa-project
spec:
  healthCheck:
    type: HTTP
    port: 9000
    requestPath: /health/ready